enum RouteModel {
  route1(
    title: "BUP-Uttara",
    image: "BUS_ROUTE_STD-0.png",
    start: "BUP",
    stops_in_order: [
      "Kalshi",
      "ECB",
      "Shewra",
      "Khilkhet",
      "Kawla",
      "Airport",
      "Jashimuddin",
      "Rajlakkhi",
      "Ajamper"
    ],
    end: "House Building",
  ),
  route2(
    title: "BUP-JFP-Kakrail",
    image: "BUS_ROUTE_STD-1.png",
    start: "BUP",
    stops_in_order: [
      "DOHS",
      "ECB Canteen",
      "ECB Chattar",
      "Shewra",
      "Bisso Road",
      "JFP",
      "Shahjadpur",
      "Uttar Badda",
      "Gulshan Link Road",
      "Middle Badda",
      "Rampura Bridge",
      "Rampura Bazar",
      "Abul Hotel",
      "Malibag Railgate",
      "Mouchak"
    ],
    end: "Kakrail",
  ),
  route3(
    title: "BUP-Maghbazar-Kakrail",
    image: "BUS_ROUTE_STD-2.png",
    start: "BUP",
    stops_in_order: [
      "DOHS",
      "ECB Canteen",
      "ECB Chattar",
      "Navy HQ",
      "Kakali",
      "Chairman Bari",
      "Mahakhali",
      "Nabisco",
      "Sat Rasta",
      "Hatirjheel",
      "Maghbazar"
    ],
    end: "Kakrail",
  ),
  route4(
    title: "BUP-Shahbagh",
    image: "BUS_ROUTE_STD-3.png",
    start: "BUP",
    stops_in_order: [
      "DOHS",
      "ECB Canteen",
      "Khalsi",
      "ECB Chattar",
      "Matikata",
      "Zia Colony",
      "CMH",
      "Army HQ",
      "CSD",
      "Post Office",
      "Adamji",
      "Workshop",
      "Shahid Jahangir Gate",
      "Bijoy Sarani",
      "Farmgate",
      "Karwan Bazar",
      "Bangla Motor"
    ],
    end: "Shahbagh",
  ),
  route5(
    title: "BUP-Khamar Bari Mor",
    image: "BUS_ROUTE_STD-4.png",
    start: "BUP",
    stops_in_order: [
      "Mirpur 12",
      "Mirpur 11.5",
      "Mirpur 11",
      "Mirpur 10",
      "Kazipara",
      "Shewrapara",
      "Taltola",
      "Agargaon",
      "Krishi University",
      "Chandrima Uddan"
    ],
    end: "Khamar Bari Mor",
  ),
  route6(
    title: "BUP-City College",
    image: "BUS_ROUTE_STD-0.png",
    start: "BUP",
    stops_in_order: [
      "Mirpur 12",
      "Mirpur 11.5",
      "Mirpur 11",
      "Proshika",
      "Commerce College",
      "Sony Hall",
      "Mirpur 01",
      "Ansar Camp",
      "Bangla College",
      "Technical",
      "Kallyanpur",
      "Shamoli",
      "Asad Gate",
      "College Gate",
      "Genetic Plaza",
      "Agora",
      "Sankar",
      "Dhanmondi 15 No Road",
      "Dhanmondi 8 No Road",
      "RGB 8 No Gate"
    ],
    end: "City College",
  ),
  route7(
    title: "BUP-City College",
    image: "BUS_ROUTE_STD-7.png",
    start: "BUP",
    stops_in_order: [
      "Mirpur 12",
      "Mirpur 11.5",
      "Mirpur 11",
      "Proshika",
      "Commerce College",
      "Sony Hall",
      "Mirpur 01",
      "Ansar Camp",
      "Bangla College",
      "Technical",
      "Kallyanpur",
      "Shamoli",
      "Asad Gate",
      "College Gate",
      "Genetic Plaza",
      "Agora",
      "Sankar",
      "Dhanmondi 15 No Road",
      "Dhanmondi 8 No Road",
      "RGB & No Gate"
    ],
    end: "City College",
  );

  const RouteModel({
    required this.title,
    required this.image,
    required this.start,
    required this.stops_in_order,
    required this.end,
  });

  final String title;
  final String image;
  final String start;
  final List<String> stops_in_order; // Changed this to a List of Strings
  final String end;
}
