// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBZnpnhn0ka4kvJzL4d2mJV2HU8B7ch_8',
    appId: '1:71119838777:web:6648358d5034625d4d37e8',
    messagingSenderId: '71119838777',
    projectId: 'bus-tracker-bbaa6',
    authDomain: 'bus-tracker-bbaa6.firebaseapp.com',
    storageBucket: 'bus-tracker-bbaa6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgodKDPN2hJc8nUoMxiETzoBPDmCWL8Nk',
    appId: '1:71119838777:android:f0ce8325eabc00734d37e8',
    messagingSenderId: '71119838777',
    projectId: 'bus-tracker-bbaa6',
    storageBucket: 'bus-tracker-bbaa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEydRg_ZBetKkxfuU5-smcy_WUQVkYQk4',
    appId: '1:71119838777:ios:b997eef200f94d144d37e8',
    messagingSenderId: '71119838777',
    projectId: 'bus-tracker-bbaa6',
    storageBucket: 'bus-tracker-bbaa6.firebasestorage.app',
    iosBundleId: 'com.example.busTrackerUserApp',
  );
}
